SOURCES=$(wildcard src/*.c)
OBJECTS=$(foreach I,$(SOURCES:.c=.o),build/$(notdir $I))

all: $(OUTFILE)

$(OUTFILE): out build $(OBJECTS)
	$(GCC) -o $(OUTFILE) $(OBJECTS) $(STATICLIBS) $(LDFLAGS) 

build/%.o: src/%.c
	$(GCC) $(GCCFLAGS) -I./include $(foreach x,$(INCLUDES),-I$x) -c $< -o $@

out:
	mkdir out

build:
	mkdir build

clean:
	rm -rf build out

